import { FieldMetadataType } from 'twenty-shared/types';

import { CreateFieldInput } from 'src/engine/metadata-modules/field-metadata/dtos/create-field.input';

export const getDevSeedCompanyCustomFields = (
  objectMetadataId: string,
  workspaceId: string,
): CreateFieldInput[] => {
  return [
    {
      workspaceId,
      type: FieldMetadataType.TEXT,
      name: 'tagline',
      label: 'Tagline',
      description: "Company's Tagline",
      icon: 'IconAdCircle',
      isActive: true,
      isNullable: false,
      isUnique: false,
      defaultValue: "''",
      objectMetadataId,
    },
    {
      workspaceId,
      type: FieldMetadataType.LINKS,
      name: 'introVideo',
      label: 'Intro Video',
      description: "Company's Intro Video",
      icon: 'IconVideo',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
    },
    {
      workspaceId,
      type: FieldMetadataType.MULTI_SELECT,
      name: 'workPolicy',
      label: 'Work Policy',
      description: "Company's Work Policy",
      icon: 'IconHome',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      options: [
        {
          color: 'green',
          label: 'On-Site',
          position: 0,
          value: 'ON_SITE',
        },
        {
          color: 'turquoise',
          label: 'Hybrid',
          position: 1,
          value: 'HYBRID',
        },
        {
          color: 'sky',
          label: 'Remote Work',
          position: 2,
          value: 'REMOTE_WORK',
        },
      ],
    },
  {
      workspaceId,
      type: FieldMetadataType.BOOLEAN,
      name: 'visaSponsorship',
      label: 'Visa Sponsorship',
      description: "Company's Visa Sponsorship Policy",
      icon: 'IconBrandVisa',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      defaultValue: false,
  },
  {
      workspaceId,
      type: FieldMetadataType.MULTI_SELECT,
      name: 'roofType',
      label: 'Roof Type',
      description: "Primary roof type of client's property",
      icon: 'IconHome',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      options: [
        { color: 'blue', label: 'Asphalt Shingle', position: 0, value: 'ASPHALT_SHINGLE' },
        { color: 'gray', label: 'Metal', position: 1, value: 'METAL' },
        { color: 'red', label: 'Tile', position: 2, value: 'TILE' },
        { color: 'orange', label: 'Slate', position: 3, value: 'SLATE' },
        { color: 'green', label: 'Flat', position: 4, value: 'FLAT' },
      ],
  },
  {
      workspaceId,
      type: FieldMetadataType.NUMBER,
      name: 'yearsInBusiness',
      label: 'Years in Business',
      description: 'How many years the company has been in business',
      icon: 'IconCalendar',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
  },
  {
      workspaceId,
      type: FieldMetadataType.TEXT,
      name: 'serviceArea',
      label: 'Service Area',
      description: 'Main service area of the company',
      icon: 'IconMapPin',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
  },
  {
      workspaceId,
      type: FieldMetadataType.TEXT,
      name: 'licenseNumber',
      label: 'License Number',
      description: 'Roofing license number',
      icon: 'IconId',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
  },
  {
      workspaceId,
      type: FieldMetadataType.BOOLEAN,
      name: 'insured',
      label: 'Insured',
      description: 'Whether the company is insured',
      icon: 'IconShieldCheck',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      defaultValue: false,
  },
  ];
};

export const getDevSeedPeopleCustomFields = (
  objectMetadataId: string,
  workspaceId: string,
): CreateFieldInput[] => {
  return [
    {
      workspaceId,
      type: FieldMetadataType.TEXT,
      name: 'intro',
      label: 'Intro',
      description: "Contact's Intro",
      icon: 'IconNote',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
    },
    {
      workspaceId,
      type: FieldMetadataType.PHONES,
      name: 'whatsapp',
      label: 'Whatsapp',
      description: "Contact's Whatsapp Number",
      icon: 'IconBrandWhatsapp',
      isActive: true,
      isNullable: false,
      isUnique: false,
      defaultValue: {
        primaryPhoneNumber: "''",
        primaryPhoneCountryCode: "'FR'",
        primaryPhoneCallingCode: "'+33'",
        additionalPhones: null,
      },
      objectMetadataId,
    },
    {
      workspaceId,
      type: FieldMetadataType.MULTI_SELECT,
      name: 'workPreference',
      label: 'Work Preference',
      description: "Person's Work Preference",
      icon: 'IconHome',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      options: [
        {
          color: 'green',
          label: 'On-Site',
          position: 0,
          value: 'ON_SITE',
        },
        {
          color: 'turquoise',
          label: 'Hybrid',
          position: 1,
          value: 'HYBRID',
        },
        {
          color: 'sky',
          label: 'Remote Work',
          position: 2,
          value: 'REMOTE_WORK',
        },
      ],
    },
  {
      workspaceId,
      type: FieldMetadataType.RATING,
      name: 'performanceRating',
      label: 'Performance Rating',
      description: "Person's Performance Rating",
      icon: 'IconStars',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      options: [
        {
          label: '1',
          value: 'RATING_1',
          position: 0,
        },
        {
          label: '2',
          value: 'RATING_2',
          position: 1,
        },
        {
          label: '3',
          value: 'RATING_3',
          position: 2,
        },
        {
          label: '4',
          value: 'RATING_4',
          position: 3,
        },
        {
          label: '5',
          value: 'RATING_5',
          position: 4,
        },
      ],
  },
  {
      workspaceId,
      type: FieldMetadataType.MULTI_SELECT,
      name: 'roofCondition',
      label: 'Roof Condition',
      description: "Current condition of the client's roof",
      icon: 'IconHome',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      options: [
        { color: 'green', label: 'New', position: 0, value: 'NEW' },
        { color: 'blue', label: 'Good', position: 1, value: 'GOOD' },
        { color: 'orange', label: 'Needs Repair', position: 2, value: 'NEEDS_REPAIR' },
        { color: 'red', label: 'Leaking', position: 3, value: 'LEAKING' },
        { color: 'brown', label: 'Replace', position: 4, value: 'REPLACE' },
      ],
  },
  {
      workspaceId,
      type: FieldMetadataType.SELECT,
      name: 'preferredShingleColor',
      label: 'Preferred Shingle Color',
      description: "Customer's preferred shingle color",
      icon: 'IconPalette',
      isActive: true,
      isNullable: true,
      isUnique: false,
      objectMetadataId,
      options: [
        { color: 'brown', label: 'Brown', position: 0, value: 'BROWN' },
        { color: 'gray', label: 'Gray', position: 1, value: 'GRAY' },
        { color: 'black', label: 'Black', position: 2, value: 'BLACK' },
        { color: 'red', label: 'Red', position: 3, value: 'RED' },
      ],
  },
  ];
};
